// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCpB_Sjwaj0l3-GwZa-Y1BO6lPXEAdL5Y',
    appId: '1:607718997747:web:7787bb310e07fdc867c186',
    messagingSenderId: '607718997747',
    projectId: 'cocoon-booking',
    authDomain: 'cocoon-booking.firebaseapp.com',
    storageBucket: 'cocoon-booking.firebasestorage.app',
    measurementId: 'G-093WS2VE4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK2w-YvDvBOLSTCRwLcroc12Ro_vuaVNU',
    appId: '1:607718997747:android:26c4b7cf40e1f88567c186',
    messagingSenderId: '607718997747',
    projectId: 'cocoon-booking',
    storageBucket: 'cocoon-booking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2cKAiNJDZnQPLf54-u-rsOR9CTsTZ_W0',
    appId: '1:607718997747:ios:31ab46e91cd1fd6767c186',
    messagingSenderId: '607718997747',
    projectId: 'cocoon-booking',
    storageBucket: 'cocoon-booking.firebasestorage.app',
    androidClientId: '607718997747-4stp4p1bbarjb4se0uvrrtl558knikan.apps.googleusercontent.com',
    iosClientId: '607718997747-diu6oc04r2lmu5pegf3jn0gb8bnve9vc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cocoonAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2cKAiNJDZnQPLf54-u-rsOR9CTsTZ_W0',
    appId: '1:607718997747:ios:31ab46e91cd1fd6767c186',
    messagingSenderId: '607718997747',
    projectId: 'cocoon-booking',
    storageBucket: 'cocoon-booking.firebasestorage.app',
    androidClientId: '607718997747-4stp4p1bbarjb4se0uvrrtl558knikan.apps.googleusercontent.com',
    iosClientId: '607718997747-diu6oc04r2lmu5pegf3jn0gb8bnve9vc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cocoonAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCpB_Sjwaj0l3-GwZa-Y1BO6lPXEAdL5Y',
    appId: '1:607718997747:web:49ea76940429397c67c186',
    messagingSenderId: '607718997747',
    projectId: 'cocoon-booking',
    authDomain: 'cocoon-booking.firebaseapp.com',
    storageBucket: 'cocoon-booking.firebasestorage.app',
    measurementId: 'G-V5HWB6V3BN',
  );
}
